apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 1000
      targetPort: 1000
      nodePort: 31000